swagger: "2.0"
info: 
  description: "This is the documentation of Epic Mail API hosted on Heroku"
  version: "1.0.0"
  title: "Epic Mail"
  host: "epik-mail.herokuapp.com"
  basePath: "/api/v1"
  tags:
    - name: "messages"
    - description: "Access to access Epic Mail API endpoint"

  schemes:
    - "https"  

path: 
  /messages:
    get:
      tags:
       - "messages"
       summary: "Get all Email Messages"
       description: "returns all the messages"
       produces: 
       - "application/json"
       operationId: getAllMessages
    parameters:
       - name: search
         in: query
         description: keywords for 
         required: false
         type: string
       - name: page
         in: query
         description: page number for pagination
         required: false
         type: number
    responses:
        '200':
          description: success response
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: array
                items:
                  $ref: "#/definitions/messages"
    

